
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ChargingConnector_Id.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ChargingPool_Id.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ChargingStation_Id.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.RequestStatus.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatRequest.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatResponse.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.SetEVSEAvailabilityStatusRequest.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.CPOClient.#ctor(System.String,org.GraphDefined.WWCP.eMIPv0_7_4.CPO.CPOClient.CPOClientLogger,System.String,org.GraphDefined.Vanaheimr.Hermod.IPPort,System.Net.Security.RemoteCertificateValidationCallback,System.Net.Security.LocalCertificateSelectionCallback,System.Security.Cryptography.X509Certificates.X509Certificate,System.String,System.String,System.String,System.String,System.Nullable{System.TimeSpan},System.Nullable{System.Byte},org.GraphDefined.Vanaheimr.Hermod.DNS.DNSClient)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~F:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.CPOClient._CustomSendHeartbeatSOAPRequestMapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ACustomData.#ctor(System.Collections.Generic.IReadOnlyDictionary{System.String,System.Object})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ChargingConnector_Id.Parse(System.String)~org.GraphDefined.WWCP.eMIPv0_7_4.ChargingConnector_Id")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ChargingPool_Id.Parse(System.String)~org.GraphDefined.WWCP.eMIPv0_7_4.ChargingPool_Id")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ChargingStation_Id.Parse(System.String)~org.GraphDefined.WWCP.eMIPv0_7_4.ChargingStation_Id")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.ACustomDataBuilder.#ctor(System.Collections.Generic.IReadOnlyDictionary{System.String,System.Object})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatRequest.TryParse(System.Xml.Linq.XElement,org.GraphDefined.Vanaheimr.Hermod.SOAP.CustomXMLParserDelegate{org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatRequest},org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatRequest@,org.GraphDefined.Vanaheimr.Illias.OnExceptionDelegate)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatResponse.TryParse(org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatRequest,System.Xml.Linq.XElement,org.GraphDefined.Vanaheimr.Hermod.SOAP.CustomXMLParserDelegate{org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatResponse},org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatResponse@,org.GraphDefined.Vanaheimr.Illias.OnExceptionDelegate)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.SetEVSEAvailabilityStatusRequest.TryParse(System.Xml.Linq.XElement,org.GraphDefined.Vanaheimr.Hermod.SOAP.CustomXMLParserDelegate{org.GraphDefined.WWCP.eMIPv0_7_4.CPO.SetEVSEAvailabilityStatusRequest},org.GraphDefined.WWCP.eMIPv0_7_4.CPO.SetEVSEAvailabilityStatusRequest@,org.GraphDefined.Vanaheimr.Illias.OnExceptionDelegate)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.CPOClient.SendHeartbeat(org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatRequest)~System.Threading.Tasks.Task{org.GraphDefined.Vanaheimr.Hermod.HTTP.HTTPResponse{org.GraphDefined.WWCP.eMIPv0_7_4.CPO.HeartbeatResponse}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "RCS1001:Add braces.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.RequestStatus.CompareTo(System.Object)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1168:Parameter name differs from base name.", Justification = "<Pending>", Scope = "member", Target = "~M:org.GraphDefined.WWCP.eMIPv0_7_4.CPO.SetEVSEAvailabilityStatusRequest.Equals(org.GraphDefined.WWCP.eMIPv0_7_4.CPO.SetEVSEAvailabilityStatusRequest)~System.Boolean")]

